import type { EnemyDefinition } from "../game/content/types";

export const ENEMIES: EnemyDefinition[] = [
  {
    id: "sumslinger",
    name: "Sumslinger",
    epithet: "Quick on the plus sign",
    type: "normal",
    maxHp: 18,
    intents: [
      { id: "jab", type: "attack", value: 4, label: "Quick Sum", description: "Deal 4 damage." },
      { id: "brace", type: "defend", value: 3, label: "Carry One", description: "Gain 3 armor." },
      {
        id: "shot",
        type: "attack",
        value: 6,
        label: "Long Addition",
        description: "Deal 6 damage.",
      },
    ],
  },
  {
    id: "ledger-wisp",
    name: "Ledger Wisp",
    epithet: "Balances books and bones",
    type: "normal",
    maxHp: 17,
    intents: [
      {
        id: "paper-cut",
        type: "attack",
        value: 4,
        label: "Paper Cut",
        description: "Deal 4 damage.",
      },
      {
        id: "audit",
        type: "weaken",
        value: 2,
        label: "Audit",
        description: "Your next hit deals 2 less damage.",
      },
      {
        id: "reconcile",
        type: "heal",
        value: 4,
        label: "Reconcile",
        description: "Recover 4 health.",
      },
    ],
  },
  {
    id: "divide-hydra",
    name: "Divide Hydra",
    epithet: "Every answer grows a head",
    type: "normal",
    maxHp: 21,
    intents: [
      {
        id: "bite",
        type: "attack",
        value: 5,
        label: "Remainder Bite",
        description: "Deal 5 damage.",
      },
      {
        id: "scales",
        type: "defend",
        value: 4,
        label: "Common Denominator",
        description: "Gain 4 armor.",
      },
      {
        id: "snap",
        type: "attack",
        value: 7,
        label: "Improper Fraction",
        description: "Deal 7 damage.",
      },
    ],
  },
  {
    id: "clockwork-adder",
    name: "Clockwork Adder",
    epithet: "Its gears count down",
    type: "normal",
    maxHp: 19,
    intents: [
      { id: "tick", type: "attack", value: 4, label: "Tick", description: "Deal 4 damage." },
      { id: "tock", type: "attack", value: 5, label: "Tock", description: "Deal 5 damage." },
      { id: "wind", type: "defend", value: 5, label: "Wind Up", description: "Gain 5 armor." },
    ],
  },
  {
    id: "prime-warden",
    name: "Prime Warden",
    epithet: "No factors. No mercy.",
    type: "elite",
    maxHp: 26,
    intents: [
      {
        id: "prime-strike",
        type: "attack",
        value: 8,
        label: "Prime Strike",
        description: "Deal 8 damage.",
      },
      {
        id: "indivisible",
        type: "defend",
        value: 7,
        label: "Indivisible",
        description: "Gain 7 armor.",
      },
      {
        id: "proof",
        type: "weaken",
        value: 3,
        label: "Proof by Pain",
        description: "Your next hit deals 3 less damage.",
      },
    ],
  },
  {
    id: "compound-golem",
    name: "Compound Golem",
    epithet: "Interest accrues hourly",
    type: "elite",
    maxHp: 28,
    intents: [
      {
        id: "collection",
        type: "attack",
        value: 7,
        label: "Collection",
        description: "Deal 7 damage.",
      },
      {
        id: "interest",
        type: "heal",
        value: 6,
        label: "Compound Interest",
        description: "Recover 6 health.",
      },
      {
        id: "late-fee",
        type: "attack",
        value: 10,
        label: "Late Fee",
        description: "Deal 10 damage.",
      },
    ],
  },
  {
    id: "final-examiner",
    name: "The Final Examiner",
    epithet: "Show every step",
    type: "boss",
    maxHp: 32,
    passive: {
      name: "Show Your Work",
      description: "Exact answers deal +2 damage.",
      exactDamageBonus: 2,
    },
    intents: [
      { id: "red-ink", type: "attack", value: 9, label: "Red Ink", description: "Deal 9 damage." },
      {
        id: "curve",
        type: "heal",
        value: 7,
        label: "Grade Curve",
        description: "Recover 7 health.",
      },
      {
        id: "closed-book",
        type: "defend",
        value: 8,
        label: "Closed Book",
        description: "Gain 8 armor.",
      },
      {
        id: "deduction",
        type: "weaken",
        value: 3,
        label: "Point Deduction",
        description: "Your next hit deals 3 less damage.",
      },
    ],
  },
];
